version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/ruby:2.6.3
        environment:
          RAILS_ENV: test
  node:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:12.9.1-buster

commands:
  restore_gem:
    steps:
      - restore_cache:
          name: Restore gem dependencies
          key: v1-gem-{{ checksum "beagile_api/Gemfile.lock" }}
  save_gem:
    steps:
      - save_cache:
          name: Cache gem dependencies
          key: v1-gem-{{ checksum "beagile_api/Gemfile.lock" }}
          paths:
            - beagile_api/vendor/bundle
  restore_node_modules:
      - restore_cache:
          name: Restore node modules
          key: v1-node_modules-{{ checksum "front/be-agile/package-lock.json" }}
  save_node_modules:
    steps:
      - save_cache:
          name: Cache node modules
          key: v1-node_modules-{{ checksum "front/be-agile/package-lock.json" }}
          paths:
            - front/be-agile/node_modules

jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - restore_gem
      - run:
          name: Install gem dependencies
          working_directory: beagile_api
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3
      - save_gem
  setup_node:
    executor:
      name: node
    steps:
      - checkout
      - restore_node_modules
      - run:
          name: Install node modules
          working_directory: front/be-agile
          command: npm install
      - save_node_modules
  rubocop:
    executor:
      name: default
    steps:
      - checkout
      - restore_gem
      - run:
          name: Bundle check
          working_directory: beagile_api
          command: bundle check --path=vendor/bundle
      - run:
          name: Rubocop
          working_directory: beagile_api
          command: bundle exec rubocop
  production_build:
    executor:
      name: node
    steps:
      - checkout
      - restore_node_modules
      - run:
          name: production build
          working_directory: front/be-agile
          command: npm run build:prod

workflows:
  setup_and_rubocop:
    jobs:
      - setup
      - rubocop:
          requires: [setup]
  setup_node_and_production_build:
    jobs:
      - setup_node
      - production_build:
          requires: [setup_node]
